# This workflow will build a Java project with Ant
name: Build on Linux CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Debian dependencies
      run: |
        sudo apt update 
        sudo apt install -y liblocale-gettext-perl libtext-wrapi18n-perl libunicode-linebreak-perl libtest-pod-perl libyaml-tiny-perl
        sudo apt install -y cpanminus gettext docbook-xml docbook-xsl docbook xsltproc 
        sudo apt install -y texlive-binaries texlive-latex-base opensp libsgmls-perl
    - name: Install CPAN dependencies
      run: |
        sudo cpanm Locale::gettext
        sudo cpanm http://search.cpan.org/CPAN/authors/id/R/RA/RAAB/SGMLSpm-1.1.tar.gz
        sudo cpanm Text::WrapI18N
        sudo cpanm Unicode::GCString

        sudo cpanm -v --installdeps --notest .

    - name: Build
      run: |
        sudo perl Build.PL
        sudo ./Build verbose=1

    - name: Test
      run: ./Build test verbose=1
